#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0

plugin: amazon.aws.aws_ec2
boto_profile: exchange_clients
regions:
  - eu-west-1
include_filters:
  - tag:Name:
      - 'tc3-client-lowrate'
      - 'tc5-client-lowrate'
  - tag:Name:
      - 'tc3-client-highrate'
      - 'tc5-client-highrate'
hostnames:
  - name: tag:Name
    separator: ''
compose:
  # Use the private IP address to connect to the host
  # (note: this does not modify inventory_hostname, which is set via I(hostnames))
  ansible_host: public_ip_address
keyed_groups:
  - key: tags.Application
    separator: ''

