#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0

plugin: amazon.aws.aws_ec2
regions:
  - ap-northeast-1
include_filters:
  - tag:Name:
      - 'm5zn-metal'
      - 'c6a-12xlarge'
      - 'c6i-12xlarge'
      - 'c7i-12xlarge'
      - 'm7a-12xlarge'
      - 'm7i-12xlarge'
      - 'r7a-12xlarge'
      - 'r7i-12xlarge'
hostnames:
  - name: tag:Name
    separator: ''
compose:
  # Use the private IP address to connect to the host
  # (note: this does not modify inventory_hostname, which is set via I(hostnames))
  ansible_host: public_ip_address
keyed_groups:
  - key: tags.Application
    separator: ''

