#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0

---
- name: deploy application
  hosts: aws_ec2
  collections:
    - amazon.aws.ec2_instance
  tasks:
  - name: deploy mock trading server
    copy:
      src: ../../mock-trading-server/
      dest: /home/ec2-user/mock-trading-server/
      owner: ec2-user
      group: ec2-user
      mode: 0644
    tags:
      - deploy
  - name: install make
    become: yes
    become_user: root
    ansible.builtin.dnf:
      name: make
      state: latest
    tags:
      - make
  - name: install gcc
    become: yes
    become_user: root
    ansible.builtin.dnf:
      name: gcc
      state: latest
    tags:
      - gcc
  - name: install patch
    become: yes
    become_user: root
    ansible.builtin.dnf:
      name: patch
      state: latest
    tags:
      - patch
  - name: install glibc-devel
    become: yes
    become_user: root
    ansible.builtin.dnf:
      name: glibc-devel
      state: latest
    tags:
      - glibc-devel
  - name: Download Rust Installer
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust
  - name: install rust/cargo
    shell: /tmp/sh.rustup.rs -y
    tags:
      - rust
  - name: build exchange server
    shell: |
      [ -f ~/.cargo/env ] && source $HOME/.cargo/env
      cd $HOME/mock-trading-server/
      cargo build --release
