#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0

---
- name: update_highrates
  hosts: aws_ec2
  vars:
    exchange_servers:
      tc3-client-highrate: replace_me_with_matching_engine_host_or_ip_address
      tc3-client-lowrate: replace_me_with_matching_engine_host_or_ip_address
      tc5-client-highrate: replace_me_with_matching_engine_host_or_ip_address
      tc5-client-lowrate: replace_me_with_matching_engine_host_or_ip_address
    http_ports:
      tc3-client-highrate: replace_me_with_matching_engine_port
      tc5-client-highrate: replace_me_with_matching_engine_port
      tc3-client-lowrate: replace_me_with_matching_engine_port
      tc5-client-lowrate: replace_me_with_matching_engine_port
    connection_count:
      tc3-client-highrate: replace_me_with_desired_number_of_connection_count
      tc5-client-highrate: replace_me_with_desired_number_of_connection_count
      tc3-client-lowrate: replace_me_with_desired_number_of_connection_count
      tc5-client-lowrate: replace_me_with_desired_number_of_connection_count
  collections:
    - amazon.aws.ec2_instance
  tasks:
    - name: copy run script to ec2
      copy:
        src: ../../src/main/resources/config.properties
        dest: /home/ec2-user/config.properties
        owner: ec2-user
        group: ec2-user
    - name: "set exchange host address"
      become: yes
      become_user: root
      replace:
        path: /home/ec2-user/config.properties
        regexp: '(^HOST=)(.*)$'
        replace: 'HOST={{ exchange_servers[inventory_hostname] }}'
        backup: no
    - name: "increase exchange client count in high rate clients"
      become: yes
      become_user: root
      replace:
        path: /home/ec2-user/config.properties
        regexp: '(^EXCHANGE_CLIENT_COUNT=)(.*)$'
        replace: 'EXCHANGE_CLIENT_COUNT={{ connection_count[inventory_hostname] }}'
        backup: no
    - name: "set exchange http port"
      become: yes
      become_user: root
      replace:
        path: /home/ec2-user/config.properties
        regexp: '(^HTTP_PORT=)(.*)$'
        replace: 'HTTP_PORT={{ http_ports[inventory_hostname] }}'
        backup: no
    - name: "set exchange port"
      become: yes
      become_user: root
      replace:
        path: /home/ec2-user/config.properties
        regexp: '(^WEBSOCKET_PORT=)(.*)$'
        replace: 'WEBSOCKET_PORT={{ http_ports[inventory_hostname] }}'
        backup: yes
