#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0

---
- name: deploy application
  hosts: aws_ec2
  vars_files:
    - instance_config.yaml
  collections:
    - amazon.aws.ec2_instance
  tasks:
  - name: Deploy Mock Trading Server
    copy:
      src: ../../mock-trading-server/
      dest: /home/ec2-user/mock-trading-server/
      owner: ec2-user
      group: ec2-user
      mode: 0644
    tags:
      - deploy
  - name: Install Make
    become: yes
    become_user: root
    ansible.builtin.dnf:
      name: make
      state: latest
    tags:
      - make
  - name: Install gcc
    become: yes
    become_user: root
    ansible.builtin.dnf:
      name: gcc
      state: latest
    tags:
      - gcc
  - name: Install patch
    become: yes
    become_user: root
    ansible.builtin.dnf:
      name: patch
      state: latest
    tags:
      - patch
  - name: Install glibc-devel
    become: yes
    become_user: root
    ansible.builtin.dnf:
      name: glibc-devel
      state: latest
    tags:
      - glibc-devel
  - name: Install openssl-devel
    become: yes
    become_user: root
    ansible.builtin.dnf:
      name: openssl-devel
      state: latest
    tags:
      - openssl-devel
  - name: Download Rust Installer
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust
  - name: install rust/cargo
    shell: /tmp/sh.rustup.rs -y
    tags:
      - rust
  - name: Build Exchange Server
    shell: |
      [ -f ~/.cargo/env ] && source $HOME/.cargo/env
      cd $HOME/mock-trading-server/
      cargo build --release
  - name: Generate Self Signed certificates
    shell: |
      openssl genrsa -out localhost.key 2048
      openssl req -new -key localhost.key -out localhost.csr \
        -subj "/C=NL/ST=Zuid-Holland/L=city/O=amazon/OU=amazon/CN=localhost/emailAddress=random@random.nl" \
        -addext "subjectAltName = DNS:localhost" \
        -newhdr \
        -passin pass:123456 \
        -keyform PEM \
        -outform PEM
      openssl x509 -req -days 365 -in localhost.csr -signkey localhost.key -out localhost.crt
      openssl pkcs12 -export -out keystore.p12 \
      -inkey localhost.key \
      -in localhost.crt \
      -passout pass:123456
  - name: Copy Client Config properties file
    copy:
      src: ../../mock-trading-server/configuration.toml
      dest: /home/ec2-user/mock-trading-server/target/release/configuration.toml
      owner: ec2-user
      group: ec2-user
  - name: "set to use ssl"
    become: yes
    become_user: root
    replace:
      path: /home/ec2-user/mock-trading-server/target/release/configuration.toml
      regexp: '(^use_ssl=)(.*)$'
      replace: 'use_ssl="{{ use_ssl[inventory_hostname] }}"'
      backup: no
