#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0

---
- name: restart exchange client
  hosts: aws_ec2
  collections:
    - amazon.aws.ec2_instance
  tasks:
    - name: stop exchange client
      become: true
      become_user: root
      shell: |
        ps -aux | grep "java" | grep -v "grep" | awk '{print $2}' | while read -r pid ; do
          echo "Shutting down PID: $pid"
          kill -9 $pid
        done
    - name: start exchange server
      shell: "screen -dmS test bash -c 'cd /home/ec2-user/; ./run.sh > output.log 2>&1'"
      async: 45
      poll: 0
