#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0

---
- name: restart exchange client
  hosts: aws_ec2
  collections:
    - amazon.aws.ec2_instance
  tasks:
    - name: start exchange client
      shell: "screen -dmS test bash -c 'cd /home/ec2-user/; ./run.sh > output.log 2>&1'"
      async: 45
      poll: 0
