#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0

---
- name: restart exchange client
  hosts: aws_ec2
  vars_files:
    - instance_config.yaml
  collections:
    - amazon.aws.ec2_instance
  tasks:
    - name: start exchange server
      become: yes
      become_user: root
      shell: "tmux new -s test_server -d bash -c 'cd /home/ec2-user/mock-trading-server; ./target/release/mock-trading-server > output.log 2>&1'"
      async: 45
      poll: 0
    - name: start exchange client
      become: yes
      become_user: root
      shell: "tmux new -s test_client -d bash -c 'cd /home/ec2-user/; ./{{ run_script[inventory_hostname] }} > output.log 2>&1'"
      async: 45
      poll: 0
